#include "Globals.h"

double SCALE_FACTOR = 0.4;
int M_WINDOW_HEIGHT = 770 * SCALE_FACTOR;
int M_WINDOW_WIDTH = 1330 * SCALE_FACTOR;
int GRID_HEIGHT = 11;
int GRID_WIDTH = 18;
int TILE_SIZE = 70 * SCALE_FACTOR;
